[package]
name = "qr-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
qrcodegen = { version = "1.8.0" }
clap = { version = "3.2.7", features = ["derive"] }
directories = { version = "4.0.1" }
termcolor = { version = "1.1.3" }
dialoguer = { version = "0.10.1" }
atty = { version = "0.2.14" }
regex = { version = "1.5.6" }
lazy_static = { version = "1.4.0" }
